### PR TITLE
I18next slots

### PR DESCRIPTION
**Pull request by ramon-h**
Using i18next for "slot" vs "slots".

### CODE REVIEW

**Comment by ramon-h** [comment]
I tend to work in my own fork instead of just a branch. If you're having to review/approve WIP, then that might not be very efficient and I can look at workin gin a different way.

**Comment by ramon-h** [comment]
@MattRC7 fyi

**Comment by MattRC7** [comment]
I'll try to take a look this evening! And working from a fork is okay with me.

**Review by MattRC7 — APPROVED** [review]
This is excellent, thank you!

**Pull request merged**
