### PR TITLE
Google Maps links

### PR DESCRIPTION
**Pull request by ramon-h**
I found myself repeatedly looking up the locations on Google Maps. I thought a simple look would help others.

### CODE REVIEW

**Review by livgust — APPROVED** [review]

**Comment by livgust** [comment]
@ramon-h looks good! Mind fixing the conflict and I'll merge?

**Comment by ramon-h** [comment]
> @ramon-h looks good! Mind fixing the conflict and I'll merge?

Should be all set now.

**Comment by livgust** [comment]
@ramon-h looks like there's still a conflict - I'm sorry, it's probably my fault.

**Comment by ramon-h** [comment]
I think it's all set now.

**Review by livgust — APPROVED** [review]

**Pull request merged**
