### PR TITLE
Parses multiple date formats.

### PR DESCRIPTION
**Pull request by harcod**
Accepts "m/d/y" or "YYYY-MM-DD" from the backend.
Transforms both to "ddd MMM D" (For example, Tue Mar 2) for UI.

Uses 'dayjs' for date operations

### CODE REVIEW

**Comment by harcod** [comment]
I performed this modification on the `master` since it sounded like you needed it soon.

**Comment by zpeyton** [comment]
LGTM

**Comment by livgust** [comment]
@zpeyton did you test this at all? If so, could you formally approve the PR?
@harcod I saw a couple of the tests marked TODO - will those be fixed in a different PR?

**Comment by zpeyton** [comment]
> @zpeyton did you test this at all? If so, could you formally approve the PR?
I will test in the morning. Seems like they are still hashing out the UX anyway.

**Comment by harcod** [comment]
> @harcod I saw a couple of the tests marked TODO - will those be fixed in a different PR?

I created a new issue #99 to deal with this later.

**Review by zpeyton — APPROVED** [review]
Tested this by running the npm test script and it passes.

**Pull request merged**
