### PR TITLE
Update CRA to 4.0.3

### LINKED ISSUE #63: Dependency vulnerablity in react-scripts
```
                                                                                
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ immer                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=8.0.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ react-scripts                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ react-scripts > react-dev-utils > immer                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1603                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 high severity vulnerability in 2000 scanned packages
  1 vulnerability requires manual review. See the full report for details.
```

`npm audit fix` could not resolve the issue, as the dependency is nested. Looks like the `react-scripts` repo is aware, so we should track that issue and bump the version once it is resolved: https://github.com/facebook/create-react-app/issues/10578

### PR DESCRIPTION
**Pull request by dldereklee**
Fixes #63 
https://github.com/facebook/create-react-app/pull/10412#issuecomment-783579978
```
> npm audit

=== npm audit security report ===                        

found 0 vulnerabilities
```

### CODE REVIEW

**Comment by MattRC7** [comment]
I wonder if there was a reason we had the version of CRA fixed?

I'll try to get to testing this today.

**Comment by livgust** [comment]
@dldereklee mind fixing the conflict? I assume it's just keeping your changes.

**Comment by dldereklee** [comment]
Done

**Comment by iann** [comment]
Looks good to me! Verified locally and site builds as expected.

```
                       === npm audit security report ===

found 0 vulnerabilities
 in 1913 scanned packages
```

**Review by iann — APPROVED** [review]
building as expected. LTGM

**Review by iann — CHANGES_REQUESTED** [review]
Hello, looks like a conflict now on the package.json. Could you please fix?

**Comment by dldereklee** [comment]
@iann Should be resolved now

**Review by johnhawkinson — APPROVED** [review]

**Review by iann — CHANGES_REQUESTED** [review]
Can you upgrade to `npm` 7+ and run another `npm install`? I think that would reduce the number of differences on `package-lock.json` and should keep the lock file version at 2.

**Comment by dldereklee** [comment]
@iann Alright regenerated it using npm 7.6.1

**Pull request merged**
